# Generated by Django 4.2.6 on 2023-12-08 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='الأسم:')),
                ('famaily', models.CharField(blank=True, max_length=30, null=True, verbose_name='العائلة:')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='نبذة عنك:')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظه:')),
                ('numberphone', models.CharField(blank=True, max_length=14, null=True, verbose_name='رقم الهاتف:')),
                ('workhour', models.CharField(blank=True, max_length=4, null=True, verbose_name='عدد ساعات العمل :')),
                ('waittime', models.IntegerField(blank=True, null=True, verbose_name='مدة الانتظار')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True, verbose_name='من انا:')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='السعر:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profile', verbose_name='الصورة الشخصية')),
                ('spicialist', models.CharField(blank=True, max_length=50, null=True, verbose_name='متخصص في :')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
