# Generated by Django 4.2.6 on 2023-12-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='famaily',
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True, verbose_name='النوع'),
        ),
    ]
