# Generated by Django 4.2.6 on 2023-12-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_famaily_profile_type_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gmail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جميل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twiter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تويتر'),
        ),
    ]
